export interface RoleDefinition {
  name: string;
  displayName: string;
  permissions: string[];
}

/**
 * Source de vérité des rôles livrés avec Stockini.
 * Seule la présence effective d'un rôle en base autorise son attribution.
 */
export const ROLE_DEFINITIONS: readonly RoleDefinition[] = [
  {
    name: 'ADMIN',
    displayName: 'Administrateur complet',
    permissions: ['*'],
  },
  {
    name: 'SUPER_ADMIN',
    displayName: 'Super-administrateur',
    permissions: ['*'],
  },
  {
    name: 'STOCK_MANAGER',
    displayName: 'Responsable du stock',
    permissions: [
      'dashboard.view',
      'products.view',
      'products.create',
      'products.update',
      'products.import',
      'products.export',
      'products.view_margin',
      'stock.view',
      'stock.adjust',
      'stock.transfer',
      'stock.movements.view',
      'stock.export',
      'alerts.view',
      'alerts.create',
      'alerts.update',
      'alerts.delete',
      'alerts.mark_read',
      'reports.view',
      'reports.stock_stats',
      'reports.export',
      'trash.view',
      'trash.restore',
      'documentation.view',
    ],
  },
  {
    name: 'SELLER',
    displayName: 'Vendeur',
    permissions: [
      'dashboard.view',
      'clients.view',
      'clients.create',
      'clients.update',
      'clients.view_history',
      'products.view',
      'stock.view',
      'stock.movements.view',
      'sales.view',
      'sales.create',
      'sales.update',
      'sales.delete',
      'sales.view_details',
      'sales.cancel',
      'sales.print',
      'sales.view_history',
      'sales.consolidate',
      'sales.consolidation.cancel',
      'sales.line.edit_unit_price_ht',
      'documents.view',
      'documents.create',
      'documents.download',
      'documents.email',
      'documents.view_history',
      'payments.view',
      'payments.create',
      'payments.receive_client_payment',
      'caisse.view',
      'caisse.operate',
      'alerts.view',
      'alerts.mark_read',
      'documentation.view',
    ],
  },
  {
    name: 'CASHIER',
    displayName: 'Caissier',
    permissions: [
      'dashboard.view',
      'clients.view',
      'sales.view',
      'sales.view_details',
      'sales.print',
      'documents.view',
      'documents.download',
      'payments.view',
      'payments.create',
      'payments.receive_client_payment',
      'caisse.view',
      'caisse.operate',
      'caisse.close',
    ],
  },
  {
    name: 'PURCHASE_MANAGER',
    displayName: 'Responsable des achats',
    permissions: [
      'dashboard.view',
      'products.view',
      'products.view_margin',
      'stock.view',
      'stock.adjust',
      'stock.movements.view',
      'stock.export',
      'suppliers.view',
      'suppliers.create',
      'suppliers.update',
      'suppliers.export',
      'purchases.view',
      'purchases.create_order',
      'purchases.create_receipt',
      'purchases.create_invoice',
      'purchases.update',
      'purchases.validate_receipt',
      'purchases.cancel',
      'purchases.export',
      'documents.view',
      'documents.create',
      'documents.download',
      'documents.email',
      'payments.view',
      'payments.create',
      'expenses.read',
      'expenses.view',
      'expenses.create',
      'expenses.update',
      'expenses.cancel',
      'expenses.pay_supplier',
      'expenses.export',
      'reports.view',
      'reports.purchases_stats',
      'reports.stock_stats',
      'reports.export',
      'documentation.view',
    ],
  },
] as const;
